version: '3.8'
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    environment:
      - HOST_DOCKER_INTERNAL=host-gateway
    volumes:
      - open-webui:/app/backend/data
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8G
    restart: always

volumes:
  open-webui:
