run_vectors:
	g++ ./vectors/main.cpp ./vectors/polynomial.cpp ./vectors/vector.cpp -o ./vectors/main
	./vectors/main.exe
run_warehouse:
	g++ ./warehouse/main.cpp ./warehouse/Product.cpp ./warehouse/Warehouse.cpp -o ./warehouse/main
	./warehouse/main.exe